blank_issues_enabled: false
contact_links:
  - name: ➕新工作项
    url: https://github.com/it188-networkx/ops-playbook/issues/new?template=task-request.yml
    about: 如果没有工作对应 ISSUE，请在 ops-playbook 中申请新的工作项。
